### PR TITLE
Hyperlink DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates the code that generates new DOI links.

Cheers!

PS: The following code might need to be upgraded wit a reg-ex, to catch such "new" DOI links: https://github.com/getcontacts/atlas/blob/7bd48e02d669312321c479c7452d66acbb580f2f/static_data/gpcr/reformat_gpcrdbdump.py#L38-L42

Maybe as in [DOAJ/#1505/files#diff](https://github.com/DOAJ/doaj/pull/1505/files#diff-bfc3d2cf37e42b5141f386e8f61e8a02R24)? I'm not using Python productively, so I'm not sure how best to `grep` around it.

### CODE REVIEW

**Comment by RasmusFonseca** [comment]
Awesome. Thanks for the help

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by RasmusFonseca** [comment]
Since this repo is kind of new and in progress, I'm curious .. how and why did you come upon this issue?

**Comment by RasmusFonseca** [comment]
https://github.com/getcontacts/atlas/blob/cd8481ec32f92c11ca87661a9300330b361e9ebf/static_data/gpcr/reformat_gpcrdbdump.py#L41

**Comment by katrinleinweber** [comment]
Productive procrastination using https://github.com/search?q=dx.doi&s=indexed&type=Code ;-)

**Pull request merged**
